// app/faq/page.tsx — global FAQ.

import Link from "next/link";
import FAQAccordion, { type FAQGroup } from "@/components/faq/FAQAccordion";
import {
  SparklesIcon,
  ArrowRightIcon,
} from "@/components/ui/Icons";

export const metadata = {
  title: "FAQ",
  description: "Common questions about using Sarthi to plan your Indian trip.",
};

const FAQS: FAQGroup[] = [
  {
    category: "Using Sarthi",
    items: [
      {
        question: "Do I need an account to plan a trip?",
        answer:
          "No — you can use Generate, Surprise Me, and the budget tracker without signing up. An account lets us save itineraries across devices and remember your preferences.",
      },
      {
        question: "How accurate is the AI-generated itinerary?",
        answer:
          "Sarthi uses live data from Amadeus (flights + hotels), OpenWeatherMap, and the Indian Railways API to ground the plan. Day-by-day activities are generated by Claude using India-specific knowledge — they're starting points you can edit via the chat.",
      },
      {
        question: "Can I edit my itinerary after it's generated?",
        answer:
          "Yes — tap 'Edit Itinerary with Sarthi' on the itinerary view or open the floating Ask Sarthi widget. Try 'add a heritage walk on Day 2' or 'modify dates' for natural-language edits.",
      },
      {
        question: "Is Sarthi free?",
        answer:
          "Free forever for the core planner, chat, and budget tracker. We don't charge commissions on bookings or hide premium tiers behind a paywall.",
      },
    ],
  },
  {
    category: "Trips & destinations",
    items: [
      {
        question: "Which destinations does Sarthi cover?",
        answer:
          "We cover 50+ Indian destinations end-to-end — beaches, hill stations, ghats, deserts, islands, and the Northeast. International destinations are deliberately not in scope.",
      },
      {
        question: "Can I plan a multi-city trip?",
        answer:
          "Yes. In the Generate wizard, toggle 'Multi-city' on Step 2 to chain up to 12 cities. Sarthi will optimise the route and stitch in train/flight/road transfers.",
      },
      {
        question: "What's the minimum budget I should plan for?",
        answer:
          "We won't generate an itinerary below ₹1,200 per person per day. That's the floor where intercity transport, basic stays, food, and a couple of activities all fit honestly.",
      },
      {
        question: "How does the 'Surprise Me' scoring work?",
        answer:
          "We score each destination on weather (30%), travel style match (30%), budget fit (25%), and duration fit (15%) for your inputs. The top 5 land on your results page with a match % and the reasons we picked them.",
      },
    ],
  },
  {
    category: "Budget & payments",
    items: [
      {
        question: "Is the price quoted final?",
        answer:
          "Prices include flights, hotels, food, intercity transport, activities, and a 10% buffer. They exclude home-city flights, travel insurance, shopping, and alcohol. Live prices update each time you re-open an itinerary.",
      },
      {
        question: "Does Sarthi book flights and hotels for me?",
        answer:
          "Not yet. We surface live availability via Amadeus and link out to the carrier or hotel. In-app booking is on the roadmap once we clear the regulatory paperwork.",
      },
      {
        question: "Can I track expenses against my plan?",
        answer:
          "Yes — every itinerary has a paired budget at /budget. Add expenses inline with date and amount; totals and remaining update live. You can rebalance categories or add custom ones.",
      },
      {
        question: "Why are all prices in rupees?",
        answer:
          "Because we built this for India. Currency conversion adds error to the budget honesty we care about. International travellers can convert on their side.",
      },
    ],
  },
  {
    category: "Account & privacy",
    items: [
      {
        question: "Where is my data stored?",
        answer:
          "User accounts and saved itineraries sit on Supabase (Postgres + RLS). Your data is never sold or shared with third parties. Read more in our Privacy Policy.",
      },
      {
        question: "Can I delete my account?",
        answer:
          "Yes — open Profile → Account actions → Delete account. We remove all itineraries, budgets, and chat history. (Mock-only on the current build; backend deletion ships with Phase 9.)",
      },
      {
        question: "Do you use cookies?",
        answer:
          "Only essential cookies for auth and a single localStorage entry for preferences. No third-party analytics, no advertising trackers.",
      },
    ],
  },
];

export default function FAQPage() {
  return (
    <div>
      {/* Hero */}
      <section className="bg-forest-950 text-white">
        <div className="max-w-7xl mx-auto px-4 md:px-8 py-16 md:py-20">
          <span className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/10 border border-white/15 text-xs font-semibold tracking-widest uppercase backdrop-blur-sm">
            <SparklesIcon size={14} />
            Frequently asked
          </span>
          <h1 className="mt-5 text-4xl md:text-5xl font-bold tracking-tight leading-[1.05]">
            Questions, answered.
          </h1>
          <p className="mt-3 text-white/80 text-lg max-w-2xl">
            Everything we get asked about using Sarthi — picking a destination,
            building a plan, tracking the budget, managing your account.
          </p>
        </div>
      </section>

      {/* Accordion */}
      <section className="max-w-3xl mx-auto px-4 md:px-8 py-12 md:py-16">
        <FAQAccordion groups={FAQS} />
      </section>

      {/* CTA */}
      <section className="max-w-3xl mx-auto px-4 md:px-8 pb-16">
        <div className="rounded-3xl bg-gradient-to-br from-green-600 to-forest-950 text-white p-8 md:p-10">
          <p className="inline-flex items-center gap-1.5 text-xs font-semibold tracking-widest uppercase text-white/70">
            <SparklesIcon size={14} />
            Still stuck?
          </p>
          <h2 className="mt-2 text-2xl md:text-3xl font-bold tracking-tight">
            Ask Sarthi directly.
          </h2>
          <p className="mt-2 text-white/85 max-w-xl">
            The floating Ask Sarthi widget is on every page. It knows about
            destinations, itineraries, and your budget — try a question.
          </p>
          {/* Contact link hidden — /contact is disabled.
          <Link
            href="/contact"
            className="mt-5 inline-flex items-center gap-2 px-5 py-3 rounded-full bg-white text-green-700 hover:bg-cream font-semibold transition-colors"
          >
            Contact us instead
            <ArrowRightIcon size={16} />
          </Link>
          */}
        </div>
      </section>
    </div>
  );
}
